Import NumPy module

In [1]:
import numpy as np 

Populate arrays with specific numbers

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
# zeros komutu ile bie zero matrix oluşturabiliriz
# sistem 64 bit olduğu için 64 bit üzerinin kullanamıyoruz ?
array_zeros=np.zeros((5,5),dtype=np.float64) 
print(array_zeros)

# 64 bit float matriximizin her bir elemanının alabileceği maximum ve minimum değerleri ve diğer birçok bilgiyi bu şekilde görebiliriz 
print("\n",np.finfo(array_zeros[1,1].dtype))


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



In [5]:
# ones komutu ile birler matrixi oluşturabiliriz
array_ones=np.ones((5,5,5))
print(array_ones)
print(type(array_ones[0,0]))



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
<class 'numpy.ndarray'>


In [6]:
array_idetity=np.identity(5)
print(array_idetity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)
# reshape ile boyutları değiştirebiliriz 
print(two_dimensional_array.reshape(1,6))

[[ 6  5]
 [11  7]
 [ 4  8]]
[[ 6  5 11  7  4  8]]


Populate arrays with sequences of numbers

In [8]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [9]:
sequence=np.linspace(5,11,7)
print(sequence)

[ 5.  6.  7.  8.  9. 10. 11.]


Populate arrays with random numbers

In [10]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[ 73  74  94 100  94  97]


In [11]:
print("%-45s " % ("First random set "), random_integers_between_50_and_100)

random_int_num2=np.random.randint(10,49,6)
print("%-45s " % "Second Random set",random_int_num2)

rand_choose=np.random.randint(0,2,6)
print("%-45s " % "Random selection set ",rand_choose)

random_set=np.choose([0,1,0,1,0,1],[random_integers_between_50_and_100,random_int_num2])
print("%-45s " % "Our Random set created with 2 different set",random_set)

First random set                               [ 73  74  94 100  94  97]
Second Random set                              [42 30 16 45 20 28]
Random selection set                           [0 1 1 1 1 1]
Our Random set created with 2 different set    [73 30 94 45 94 28]


In [12]:
#To create random floating-point values between 0.0 and 1.0, call np.random.random. For example:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.88298478 0.93687747 0.01767454 0.611296   0.1574264  0.88204173]


Mathematical Operations on NumPy Operands

In [13]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.88298478 2.93687747 2.01767454 2.611296   2.1574264  2.88204173]


In [14]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[219 222 282 300 282 291]


In [15]:
matrix1=np.random.random((2,3))
matrix2=np.random.random_sample((3,2))

print("MAtrix1 2x3\n",matrix1,"\nMatrix2 3x2\n",matrix2)

# matrix çarpımını gerçekleştirmek için dot,matmul,@ gibi fonkisyonlar kullanılabilir 
# dot ve matmul benzer performansa sahiptir ,fakat matrix hesaplama teknikleri biraz farklıdır 
# '@' sembolü '__matmul__' ve '@='sembolü '__imatmul__' methodlarını çağırır ,bu kullanım python 3.5 ve üzeri sürümlerin için geçerlidir 
# '@' sembolü '*' işlemi ile aynı önceliğe sahiptir 

print("\nnp.matmul(matrix1,matrix2)\n", np.matmul(matrix1,matrix2))
print("\nnp.dot(matrix1,matrix2)\n", np.dot(matrix1,matrix2))
print("\nmatrix1 @ matrix2\n", matrix1 @ matrix2)

MAtrix1 2x3
 [[0.95860105 0.5800079  0.48905829]
 [0.90613068 0.49564195 0.21448873]] 
Matrix2 3x2
 [[0.24694942 0.94717826]
 [0.58873023 0.92464416]
 [0.9065783  0.65950879]]

np.matmul(matrix1,matrix2)
 [[1.02156379 1.76680525]
 [0.71001868 1.45801693]]

np.dot(matrix1,matrix2)
 [[1.02156379 1.76680525]
 [0.71001868 1.45801693]]

matrix1 @ matrix2
 [[1.02156379 1.76680525]
 [0.71001868 1.45801693]]


Task 1: Create a Linear Dataset

In [16]:
feature=np.arange(6,20)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61]


In [17]:
# bu şekilde oluşturudğumuz özellik ve labelleri birleştirerek bir tablo elde edebiliriz 
feature1=np.random.random_sample(10)
feature2=np.random.random_sample(10)
feature3=np.random.random_sample(10)
feature4=feature1*feature2/feature3
index=np.arange(0,10)

colomn_labels=['Feature1','Feature2','Feature3','Feature4','index']
colomn_datas=[feature1,feature2,feature3,feature4,index]
colomns=list(zip(colomn_labels,colomn_datas))
colomns=dict(colomns)

import pandas as pd 

data=pd.DataFrame(colomns)

data.set_index('index',inplace=True)
data



Feature1  Feature2  Feature3  Feature4
index                                        
0      0.416551  0.166832  0.672965  0.103265
1      0.518901  0.143647  0.284743  0.261775
2      0.471836  0.508252  0.801157  0.299332
3      0.020388  0.607964  0.003434  3.609307
4      0.577715  0.613148  0.905802  0.391062
5      0.953165  0.031906  0.631840  0.048132
6      0.879700  0.865542  0.429890  1.771194
7      0.775370  0.881341  0.310756  2.199041
8      0.398466  0.550475  0.401108  0.546848
9      0.408384  0.356302  0.837268  0.173789

Task 2: Add Some Noise to the Dataset

In [18]:
import random 

#noise = (np.random.random([14]) * 4) - 2

noise=[]
for i in np.random.random_sample(len(label)) :
    noise.append(i + random.choice([1,-2]))

print(noise)
print(type(noise),"\n")
label = label + noise 
print(label)
print(type(label))

[1.9596248803027971, -1.4571410348786364, 1.7063801935571075, 1.7880445982768358, -1.3911149506914198, -1.6641342681178464, -1.293386400575948, 1.0639999819067611, 1.5801550065749868, -1.9610658761303128, 1.7656885232466264, -1.66320341110933, 1.7749780057261781, 1.0437791425076557]
<class 'list'> 

[23.95962488 23.54285897 29.70638019 32.7880446  32.60888505 35.33586573
 38.7066136  44.06399998 47.58015501 47.03893412 53.76568852 53.33679659
 59.77497801 62.04377914]
<class 'numpy.ndarray'>
